services:
  db:
    image: postgres:15
    container_name: anb-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  storeapi:
    depends_on:
      - db
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: storeapi
    expose:
      - 8000
    command: uvicorn storeapi.main:app --host 0.0.0.0 --port 8000
    env_file:
      - ./.env
    environment:
      # Override .env values so the app connects to the postgres service by hostname
      - DEV_DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/dev_db
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    volumes:
      - ./:/app
    
  nginx:
    image: nginx:latest
    container_name: anb-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - storeapi

  redis:
    image: redis
    container_name: anb-redis
    ports:
      - "6379:6379"
  kafka:
    image: bitnami/kafka:3.7
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LOG_DIRS=/tmp/kraft-combined-logs
volumes:
  postgres_data: