services:
  db:
    image: postgres:15
    container_name: anb-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  storeapi:
    depends_on:
      kafka:
        condition: service_healthy
      db:
        condition: service_healthy
    build: 
      context: ./
      dockerfile: api.Dockerfile
    container_name: storeapi
    expose:
      - 8000
    command: uvicorn storeapi.main:app --host 0.0.0.0 --port 8000
    env_file:
      - ./.env
    environment:
      # Override .env values so the app connects to the postgres service by hostname
      - DEV_DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/dev_db
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    volumes:
      - ./:/app
    
  nginx:
    image: nginx:latest
    container_name: anb-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - storeapi

  redis:
    image: redis
    container_name: anb-redis
    ports:
      - "6379:6379"
  kafka:
    image: bitnamilegacy/kafka:4.0.0-debian-12-r10
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LOG_DIRS=/tmp/kraft-combined-logs
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    command:
      - /bin/bash
      - -c
      - |
        /opt/bitnami/scripts/kafka/run.sh &
        echo "⏳ Waiting for Kafka to start..."
        until kafka-topics.sh --bootstrap-server localhost:9092 --list >/dev/null 2>&1; do
            echo "⏳ Kafka not ready yet..."
          sleep 2
        done
        echo "🔄 Creating topics..."
        kafka-topics.sh --create --if-not-exists --bootstrap-server localhost:9092 --topic video_tasks --partitions 1 --replication-factor 1
        echo "✅ Done. Keeping container alive..."
        tail -f /dev/null
    healthcheck:
      test: ["CMD", "bash", "-c", "kafka-topics.sh --bootstrap-server kafka:9092 --list || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10

  worker:
    build:
      context: ./
      dockerfile: worker.Dockerfile
    container_name: anb-worker
    command: ["python", "-m", "message_broker.worker"]
    depends_on:
      kafka:
        condition: service_healthy
      db:
        condition: service_healthy

    env_file:
      - ./.env
    environment:
      - DEV_DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/dev_db
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    volumes:
      - ./:/app
volumes:
  postgres_data: